const MESSAGE_ACTION = {
	SHOW_MESSAGE: 'SHOW_MESSAGE',
	CLEAR_MESSAGE: 'CLEAR_MESSAGE',
};

const MESSAGE_TYPE = {
	SUCCESS: 'SUCCESS',
	ERROR: 'ERROR',
	NONE: 'NONE',
};

export { MESSAGE_ACTION, MESSAGE_TYPE };
